

services:
  nginx:
    build: .\nginx
    ports:
      - "80:80"
    restart: always
    tty: true
    container_name: nginx
    volumes:
      - ${APP_DIR}\www:/usr/share/nginx/html
      - ${APP_DIR}\etc\nginx\conf.d:/etc/nginx/conf.d
      - ${APP_DIR}\etc\nginx\nginx.conf:/etc/nginx/nginx.conf
      - ${APP_DIR}\log\nginx:/var/log/nginx
    networks:
      - lnmp-networks
  
  mysql5.7:
    build: .\mysql5.7
    container_name: mysql5.7
    tty: true
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${APP_DIR}\data\mysql5.7:/var/lib/mysql
      - ${APP_DIR}\data\mysql-files5.7:/var/lib/mysql-files
      - ${APP_DIR}\etc\mysql5.7\my.cnf:/etc/my.cnf
      - ${APP_DIR}\log\mysql5.7:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --bind-address=0.0.0.0
    networks:
      - lnmp-networks
      
  redis:
    build: .\redis
    container_name: redis
    tty: true
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${APP_DIR}\etc\redis\redis.conf:/etc/redis.conf
      - ${APP_DIR}\data\redis:/data
      - ${APP_DIR}\log\redis:/var/log
    networks:
      - lnmp-networks

  php7.4:
    build: .\php7.4
    tty: true
    restart: always
    container_name: php7.4
    ports:
      - "9000:9000"
    volumes:
      - ${APP_DIR}\www:/var/www/html
      - ${APP_DIR}\log\php7.4:/var/log/php
      - ${APP_DIR}\etc\php7.4\php.ini:/usr/local/etc/php/php.ini
      - ${APP_DIR}\etc\php7.4\www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${APP_DIR}\etc\php7.4\conf.d:/usr/local/etc/php/conf.d
    depends_on:
      - nginx
      - mysql5.7
    networks:
      - lnmp-networks
      

networks:
  lnmp-networks:
