FROM elasticsearch:7.9.1
 
# container creator
LABEL maintainer="liu_xiao_guo@yahoo.com"
 
# copy the configuration file into the container
# COPY elasticsearch.yml /usr/share/elasticsearch/config
 
# expose the default Elasticsearch port
EXPOSE 9200 9300
